### ISSUE TITLE
Should not convert `amount` to number in javascript

### ISSUE THREAD

**Issue by boylove142** [ontio/ontology-ts-sdk#110]
Sorry to point this out, but I don't think we should convert `amount` to number in javascript since according to this stackoverflow: [what is JavaScript's highest integer value that a number can go to without losing precision?](https://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin), the actual amount to be transfered will not precise.

https://github.com/ontio/ontology-ts-sdk/blob/8b3494928febee79a754f6faa667714c7fdd9cc5/src/smartcontract/nativevm/ontAssetTxBuilder.ts#L78

Here's my code to reproduce the problem:
```
const expectAmount = '90071992547409911';
const from = new Address('Some Address 1');
const to = new Address('Some Address 2');
const tx = makeTransferTx('ONG', from, to, expectAmount, '500', '30000');

const transferAmount = deserializeTransferTx(tx.serialize()).amount;
console.log('Expected Amount', expectAmount);   // Expected Amount 90071992547409911
console.log('Transfer Amount', transferAmount); // Transfer Amount 90071992547409900
```

**Comment by MickWang** [comment]
Thanks for your issue. Already fixed it.
 https://github.com/ontio/ontology-ts-sdk/pull/111
