### ISSUE TITLE
The encode of base-x issue

### ISSUE THREAD

**Issue by nguyenhuedang** [ontio/ontology-ts-sdk#118]
Hi, I found that the SDK using base-x for encoding/decoding, such as

https://github.com/ontio/ontology-ts-sdk/blob/28f780736f5020da0e891230cb2584b31c95896b/src/crypto/address.ts#L177-L187

However, the function `encode(source)` of base-x expects to receive the `source` as **Buffer**, not **bytes array**. Further more, in version 3.0.5, it will throw error if the parameter is not Buffer:
https://github.com/cryptocoinjs/base-x/commit/6cbf08a7d7ddc51bb1055cedc60a4dd9371ee433#diff-168726dbe96b3ce427e7fedce31bb0bc

Please update the usage of encode using base-x.
Thank you.

**Comment by boylove142** [comment]
Hi Ont team, I update the code to reproduce the problem. This must be run with base-x v3.0.5
```
const ontology = require('ontology-ts-sdk');
const HdKey = require('@ont-community/hdkey-secp256r1');

const { Address, PublicKey } = ontology.Crypto;

const xpub = [Your xpub here];
const hdKey = HdKey.fromExtendedKey(xpub);
const publicKey = new PublicKey(hdKey.derive('m/0/0/1420').toString('hex'));
const address = Address.fromPubKey(publicKey).toBase58();

console.log(address);
```

**Comment by MickWang** [comment]
https://github.com/ontio/ontology-ts-sdk/pull/119
fixed. Thank you.
