### ISSUE TITLE
missing dependencies in package.json

### ISSUE THREAD

**Issue by skkiran** [ontio/ontology-ts-sdk#14]
Tried to build as per the instructions in Readme and got errors for missing dependencies.   Using node 8.10.0.  Installed these:

`npm install utf-8-validate bufferutil`

After that i got following error:

```
ERROR in ~/ontology-ts-sdk/src/index.ts(124,3)
          TS2304: Cannot find name 'Web'.
```
I see that Web was added in the most recent commit.

**Comment by MickWang** [comment]
my mistakes. Already merged a pull request to fix this problem.Pls try again.

**Comment by skkiran** [comment]
thanks.  but i still had to run following to fix dependency issue:

npm install utf-8-validate bufferutil --save
