### ISSUE TITLE
elliptic, toArrayLike is not a function

### ISSUE THREAD

**Issue by roccomuso** [ontio/ontology-ts-sdk#147]
Guess there's a bug here:

https://github.com/ontio/ontology-ts-sdk/blob/master/src/crypto/PrivateKey.ts#L285

`sign` method of `ed25519` elliptic lib doesn't work like this:

```js
        return Buffer.concat([
            signed.R.toArrayLike(Buffer, 'be', 32),
            signed.S.toArrayLike(Buffer, 'be', 32)
        ]).toString('hex');
```

Actually `R` and `S` doesn't exists. We have `_R` and `_S`, but `toArrayLike` fn is available only for `_S`.
For R we have the property `_Rencoded` that is an array.

**Comment by roccomuso** [comment]
Don't know why it's necessary this.
Can't we simply use `elliptic` builtin methods to do so?

Like:

```js
  const hash = sha512(message)
  const signed = ed25519.sign(hash, privateKey)
  const signature = signed.toHex().toLowerCase()
  console.log(signature)
```

**Comment by backslash47** [comment]
Hello,

ed25519 is not very used right now in Ontology (as far as I know). So if there is toHex method, it might be used as you said.

I would suggest to compare the result with Java SDK to see if the result is correct.

**Comment by roccomuso** [comment]
Not very familiar with java, examples are welcomed

**Comment by roccomuso** [comment]
I can confirm my solution above works. It should replace the current ed25519 one, that is broken.

**Comment by backslash47** [comment]
Then by all means, make a PR. Thanks
