### ISSUE TITLE
get transaction id (hash)

### ISSUE THREAD

**Issue by roccomuso** [ontio/ontology-ts-sdk#148]
I'm building a transaction, How to get transaction ID/Hash locally before any broadcast happen?
The Transaction hash that will be saved on the blockchain to be clear.

I tried `getSignContent()` but it's returning a different hash.

**Comment by MickWang** [comment]
Hi, you should use `getHash` to get the transaction hash.

**Comment by roccomuso** [comment]
getHash uses getSignContent:
```javascript 
getHash() {
        return this.getSignContent();
    }
```
I'm getting different Hash than the one returned by the REST after broadcast

**Comment by MickWang** [comment]
Please use `reverseHex()` of  `utils` module to handle the result of `getHash()`, then you get the same hash of the transaction after brodcast.

**Comment by roccomuso** [comment]
@MickWang thanks. That made it.
