### ISSUE TITLE
 UnhandledPromiseRejectionWarning: 

### ISSUE THREAD

**Issue by RudrikaFichadiya** [ontio/ontology-ts-sdk#154]
In Result : 'Address...' has no balance enough to cover gas cost 10000000.

Here my from(admin) address has amount : 30
and I've passed Private key which is returned by Account object while generating address.
I am transferring amount: 1.

This error is occurs every time, with the message that transactor does not have balance enough to cover gas cost 10000000.

**Comment by MickWang** [comment]
Please make sure you have more than 0.01 ONG in your Address.

**Comment by RudrikaFichadiya** [comment]
In simple transfer between to address and from address I've got one Transactor address. Which is not generated by me. So where did that address came from. Will you please tell me something about that?

**Comment by MickWang** [comment]
The "from" address is to send the asset to the "to" address. And the transfer needs one payer address, it can be the same as "from" address. I don't know what Transactor address is, can you give more info?

**Comment by RudrikaFichadiya** [comment]
Yes,
As you've said, I've transferred 10 ONG and ONT amount to my from address and My From address and transactor address both are totally different. But the thing is that, I haven't mentioned any payer address.

I've got this response:

{ Action: 'sendrawtransaction',
  Desc: 'INTERNAL ERROR, ErrUnknown',
  Error: -1,
  Id: 290848436,
  Result: 'transactor `**address with 40-bit**` has no balance enough to cover gas cost 10000000',
 Version: '1.0.0' }
(node:22276) UnhandledPromiseRejectionWarning: Error: {"Action":"sendrawtransaction","Desc":"INTERNAL ERROR, ErrUnknown","Error":-1,"Id":290848436,"Result":"transactor that `**40-bit address**` has no balance enough to cover gas cost 10000000","Version":"1.0.0"}
    at WebsocketClient.sendRawTransaction (Path\lib\index.js:5599:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:22276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by RudrikaFichadiya** [comment]
I've generated Address by creating new address, and Transferred some ONT and ONG amount from OWallet wallet address. But in Ontology Explorer the transaction Id shows that has transferred to another address.!

**Comment by MickWang** [comment]
The error message is clear. Your payer address has no enough ONG to cover gas cost. The address  "transactor **address with 40-bit** is reversed hex string of your payer address. And please make sure  you sent transaction to the right network.

**Comment by RudrikaFichadiya** [comment]
Yes, I am currently using Testnet. For all this transfer. 
Is there any problem with, that I am transferring ONG and ONT **from** OWallet's wallet **to** my address which I've created with **create** method.

**Comment by MickWang** [comment]
> Yes, I am currently using Testnet. For all this transfer.
> Is there any problem with, that I am transferring ONG and ONT **from** OWallet's wallet **to** my address which I've created with **create** method.

No problem.
