### ISSUE TITLE
Is there any method for fee checking? 

### ISSUE THREAD

**Issue by RudrikaFichadiya** [ontio/ontology-ts-sdk#156]
There is a method to calculate fees in transaction.ts.
But it is deprecated. Is there any new method or alternative solution to calculate fee dynamically?

**Comment by MickWang** [comment]
you can use pre-execute transaction to query the fee of the transaction. Just set the second parameter as true when you send transaction to the blockchain.

**Comment by RudrikaFichadiya** [comment]
/**
 * @deprecated
 * Creates params from transaction to send with websocket
 * @param tx Transactio to send
 * @param isPreExec Decides if it is pre-execute transaction
 */
export function buildTxParam(tx: Transaction, isPreExec: boolean = false) {
    const op = isPreExec ? { PreExec: '1'} : {};
    const serialized = tx.serialize();

    return JSON.stringify(Object.assign({}, Default_params, { Data: serialized }, op));
}

Using this method? Can you please elaborate?

**Comment by RudrikaFichadiya** [comment]
How can I get Private Key from Encrypted key, Password, Salt and address?

**Comment by MickWang** [comment]
For example, when you use RestClient to send transaction. You can set the second parameter a true. ```
restClient.sendRawTransaction(tx.serialize(), true);
```

**Comment by RudrikaFichadiya** [comment]
Ok. Understood. Thanks.
