### ISSUE TITLE
Create wallet doesn't give .dat file or WIF to recover my Wallet.

### ISSUE THREAD

**Issue by RudrikaFichadiya** [ontio/ontology-ts-sdk#158]
What I have to do create Wallet file/ WIF / Menmonic? Using which method? or which steps I've to follow?

**Comment by MickWang** [comment]
https://github.com/ontio/ontology-ts-sdk/blob/master/test/bip44.test.ts
you can refer to this doc.

**Comment by RudrikaFichadiya** [comment]
There is initialized mnemonic value. The question is do I have to assign custom mnemonic and use it where the seed generation is implemented?
I am creating wallet and its identity, at that time is it possible to create and get mnemonic and .dat file and other parameters as well? If yes then how?

**Comment by MickWang** [comment]
https://github.com/bitcoinjs/bip39
You can this lib to generate random mnemonic and derive the private key to create wallet. But the process is not reversible.

**Comment by RudrikaFichadiya** [comment]
Alright. 
From above solution. I've got WIF key. 
But I can not get Mnemonic using Private key? Here is the case you are saying that it is not reversible? 
Am I getting right?
