### ISSUE TITLE
How do I Get entire wallet object.

### ISSUE THREAD

**Issue by RudrikaFichadiya** [ontio/ontology-ts-sdk#159]
I have previously created one wallet. Now I want to add accounts to it.
How can I retrieve that previously generated wallet object? to add account?

I've referred: https://github.com/ontio/ontology-ts-sdk/blob/master/src/wallet.ts
But there is wallet object is created and immediately used via this.methodName.

**Comment by MickWang** [comment]
The wallet has an array of accounts that contains the account you added to it. So you can look into the array to retrieve your account.
