### ISSUE TITLE
TypeError: this.payer.serialize is not a function

### ISSUE THREAD

**Issue by rohitsahu21** [ontio/ontology-ts-sdk#165]
when i sign transaction

TransactionBuilder.signTransaction(tx, privateKey)

**Comment by WyattMufson** [comment]
The payer you used when signing the transaction is not of type `Address`, it is a string.

Try doing:

```
const address = new Address("<BASE 58 ADDRESS HERE>");
```

And use `address` as the payer.

**Comment by rohitsahu21** [comment]
Working fine with

const address = new Crypto.Address("<BASE 58 ADDRESS HERE>");

Thank You.

**Comment by WyattMufson** [comment]
Awesome!

**Comment by WyattMufson** [comment]
If you have any other issues tag me
