### ISSUE TITLE
NodeJS Runtime Error

### ISSUE THREAD

**Issue by z0Yo** [ontio/ontology-ts-sdk#166]
When attempting to run this package in NodeJS using NPM, requiring the module throws the following error:
```
ReferenceError: regeneratorRuntime is not defined
```

Steps to reproduce:
- Install via npm or yarn
- Create a empty JS file (eg. main.js)
- Require the package module (`var Ont = require('ontology-ts-sdk');`)
- Save and run from terminal (eg. `node main.js`)

Expected result:
- Script will execute successfully

Actual result:
- Console throws the error `ReferenceError: regeneratorRuntime is not defined`

This issue was not present about 6-8 months ago when I tried it last, so not sure what changed. Using node version 10.15.0

**Comment by z0Yo** [comment]
Per suggestion from @WyattMufson tried this with version `1.0.16` and seems to be working fine. So something must have been broken after this version.

**Comment by MickWang** [comment]
We fixed it on v1.0.21. Thanks.
