### ISSUE TITLE
Update readme with correct step to install

### ISSUE THREAD

**Issue by StErMi** [ontio/ontology-ts-sdk#58]
Could you please update your build process?
Also, could you please deploy this package on npm repo?

**Comment by StErMi** [comment]
Could you also post an example that uses and integrate this SDK?

**Comment by MickWang** [comment]
hi, the build process has been updated and we have published it on npm: `ontology-ts-sdk`.
You can refer the test files to see how to use the api.
And here is a example project you can refer to.
