### ISSUE TITLE
Missing Claim abifunction schema and need a makeInvokeTransaction and buildClaimTx in transactionBuilder.ts

### ISSUE THREAD

**Issue by bobio2018** [ontio/ontology-ts-sdk#9]
Hi there, 

I am testing Claim function here,  have signed a claim object and ready to interact with ontology chain to register the claim, a few questions here:

1. looks like we are missing a json schema section for `RegisterClaim` in [/src/smartcontract/data/IdContract.abi.ts](https://github.com/ontio/ontology-ts-sdk/blob/master/src/smartcontract/data/IdContract.abi.ts)

2. also need a new helper function `makeInvokeTransaction ` in [/src/transaction/transactionBuilder.ts](https://github.com/ontio/ontology-ts-sdk/blob/master/src/transaction/transactionBuilder.ts) 
current makeInvokeTransaction is declaring `tx.type=TxType.Invoke`, which should be `TxType.Claim` for Claim Tx, assuming other parameters remain the same.

3. finally we need a new `buildClaimTx` helper function to construct the payload. Should it follow the same pattern as `buildAddAttributeTx` which takes 5 parameters to build?; Or 4 parameters without `type`, as described in [identity_claim.md](https://github.com/ontio/ontology-ts-sdk/blob/master/docs/en/identity_claim.md)

'''var param = SDK.buildClaimTx(path, value, ontid, privateKey)'''

Happy to contribute by writing/testing them then submitting a pull request, if I know the required schema for  RegisterClaim?

Thanks,
Bobio

**Comment by roccomuso** [comment]
any news on this?
